export const categories = [
    { id: 'all', name: 'सभी वेंडर', icon: '🎯', color: 'from-purple-500 to-pink-500' },
    { id: 'catering', name: 'कैटरिंग', icon: '🍽️', color: 'from-green-500 to-teal-500' },
    { id: 'decoration', name: 'डेकोरेशन', icon: '🎊', color: 'from-yellow-500 to-orange-500' },
    { id: 'mehandi', name: 'मेंहदी आर्टिस्ट', icon: '🎨', color: 'from-orange-500 to-red-500' },
    { id: 'dj', name: 'डीजे', icon: '🎧', color: 'from-cyan-500 to-blue-500' },
    { id: 'dancer', name: 'डांसर', icon: '💃', color: 'from-purple-500 to-pink-500' },
    { id: 'gifts', name: 'गिफ्ट', icon: '🎁', color: 'from-red-500 to-pink-500' },
    { id: 'makeup', name: 'मेकअप आर्टिस्ट', icon: '💄', color: 'from-pink-500 to-rose-500' },
    { id: 'flower', name: 'फूल सजावट', icon: '🌸', color: 'from-green-400 to-pink-400' },
    { id: 'garden', name: 'मैरिज गार्डन', icon: '🌳', color: 'from-green-500 to-teal-500' },
    { id: 'hotel', name: 'होटल', icon: '🏨', color: 'from-blue-500 to-indigo-500' },
    { id: 'travels', name: 'ट्रेवल्स', icon: '🚗', color: 'from-gray-500 to-gray-700' },
    { id: 'ghode', name: 'घोड़ेवाला', icon: '🐎', color: 'from-amber-500 to-orange-600' },
    { id: 'pandit', name: 'पंडितजी', icon: '🕉️', color: 'from-orange-400 to-red-500' },
    { id: 'kundli', name: 'कुंडली मिलन', icon: '📜', color: 'from-yellow-400 to-orange-500' },
    { id: 'anchor', name: 'एंकर', icon: '🎤', color: 'from-blue-400 to-purple-500' },
    { id: 'photography', name: 'फोटोग्राफर', icon: '📸', color: 'from-blue-500 to-indigo-500' },
    { id: 'event', name: 'इवेंट ऑर्गेनाइजर', icon: '🎪', color: 'from-purple-500 to-pink-600' },
    { id: 'lighting', name: 'लाइटिंग', icon: '💡', color: 'from-yellow-300 to-orange-400' },
    { id: 'band', name: 'बैंड बाजा', icon: '🎺', color: 'from-red-400 to-pink-500' },
    { id: 'cards', name: 'विवाह कार्ड', icon: '💌', color: 'from-pink-400 to-rose-500' },
    { id: 'dress_rental', name: 'विवाह ड्रेस (रेंटल)', icon: '👗', color: 'from-purple-400 to-pink-500' },
    { id: 'dress_showroom', name: 'विवाह ड्रेस शोरूम', icon: '👘', color: 'from-indigo-400 to-purple-500' },
    { id: 'jewellery_rental', name: 'ज्वेलरी (रेंटल)', icon: '💍', color: 'from-yellow-400 to-amber-500' },
    { id: 'jewellery_showroom', name: 'ज्वेलरी शोरूम', icon: '💎', color: 'from-amber-400 to-yellow-500' },
    { id: 'mithai', name: 'मिठाईवाला', icon: '🍬', color: 'from-orange-400 to-red-400' },
    { id: 'boutique', name: 'बुटीक', icon: '✂️', color: 'from-pink-400 to-purple-400' },
    { id: 'tent', name: 'टेंट हाउस', icon: '⛺', color: 'from-green-400 to-blue-400' },
    { id: 'housekeeping', name: 'हाउस किपिंग', icon: '🧹', color: 'from-teal-400 to-green-500' },
    { id: 'security', name: 'सिक्यूरिटी', icon: '🔒', color: 'from-gray-600 to-gray-800' },
    { id: 'celebrity', name: 'आर्टिस्ट/सेलिब्रिटी', icon: '⭐', color: 'from-yellow-500 to-orange-600' }
  ];